// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV8vkQO1x37oiBFyzpDi7cZeHMPkc-NAc',
    appId: '1:903758254008:web:729c82f7b3d2111ea3894d',
    messagingSenderId: '903758254008',
    projectId: 'wish-3a906',
    authDomain: 'wish-3a906.firebaseapp.com',
    storageBucket: 'wish-3a906.appspot.com',
    measurementId: 'G-BL45CL75PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjCguFrPjQzc811mDb9ml2grjN4mhajW8',
    appId: '1:903758254008:android:33674c33531d825ba3894d',
    messagingSenderId: '903758254008',
    projectId: 'wish-3a906',
    storageBucket: 'wish-3a906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATuO15NrXo8WbSw4YuKJppR861TOZ0CgI',
    appId: '1:903758254008:ios:4f6d10b95870fb22a3894d',
    messagingSenderId: '903758254008',
    projectId: 'wish-3a906',
    storageBucket: 'wish-3a906.appspot.com',
    androidClientId: '903758254008-g6b4v6t0rgt8p64thg59n2638gvo25ca.apps.googleusercontent.com',
    iosClientId: '903758254008-hrfsvmm2j163v91p4l1s4k41lrfs2pgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.wish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATuO15NrXo8WbSw4YuKJppR861TOZ0CgI',
    appId: '1:903758254008:ios:4b590f91bed07501a3894d',
    messagingSenderId: '903758254008',
    projectId: 'wish-3a906',
    storageBucket: 'wish-3a906.appspot.com',
    androidClientId: '903758254008-g6b4v6t0rgt8p64thg59n2638gvo25ca.apps.googleusercontent.com',
    iosClientId: '903758254008-t0osa2dfpjnp9phmg4fcfl4omegpup6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.wish.RunnerTests',
  );
}
